### ISSUE TITLE
Disable built in nginx-ingress controller

### ISSUE THREAD

**Issue by KaelBaldwin** [devspace-cloud/devspace-cloud#11]
There should be an option to disable the nginx ingress controller that gets deployed with devspace-cloud.

Another option is to remove it from the chart entirely, I would think it is pretty common for a cluster to already have an ingress controller set up, it seems a bit out of scope for this as well.

Why not just let whatever ingress controller is set up as the default handle any created ingresses?

**Comment by FabianKramm** [comment]
@KaelBaldwin thanks for opening this issue! There is an option called nginx-ingress.enabled in the devspace-cloud helm chart that allows disabling the ingress controller. 

Generally I think is it good to have this option in the chart, but disabling should be definitively possible. Is nginx-ingress.enabled not working for you?

**Comment by KaelBaldwin** [comment]
@FabianKramm 

Yes, I created this issue before it was decided that devspace-cloud would be exported to a helm registry, which would be my preferred way of setting it up anyways.

And it is indeed possible to disable it via the values.yaml file, which is how I installed it myself.

My thinking behind opening this issue was to make it easier for someone new deploying devspace-cloud via devspace in a similar situation to myself, to give them an opportunity to consider whether or not they need an ingress-controller installed alongside devspace. I think if the cluster is being used for anything other than devspace-cloud, it's going to be pretty common to want to disable the ingress controller. I know I wouldn't want devspace purge to bring down any other ingress routing If I decided to remove devspace-cloud.

Perhaps it is expected that most users will be using a dedicated cluster for devspace-cloud (which is probably a good choice), in which case it probably makes more sense to include the ingress-controller, but otherwise, I think it's a little strange to include one at all, especially by default.

My thinking is that a better option would simply be to mention it in the documentation and readme that an ingress controller should be installed separately if that functionality is required.

**Comment by LukasGentele** [comment]
@KaelBaldwin just for clarification: you can set the values for the chart in devspace.yaml via `deployments[1].helm.values` or if you prefer an external values.yaml file, you can add `deployments[1].helm.valuesFiles`.

However, documentation for all chart options is work in progress. For now, most of them are shown in https://github.com/devspace-cloud/devspace-cloud/blob/master/chart/values.yaml
