### ISSUE TITLE
Can't delete a space if the namespace has been deleted before

### ISSUE THREAD

**Issue by Mokto** [devspace-cloud/devspace-cloud#17]
Hi,

I created a space, that created a namespace in Kubernetes.
A few days later I've deleted that namespace with `kubectl delete ns ...`.

Now the space is still existing and I can't `devspace use space ....` because the serviceaccount doesn't exist anymore.
But I also can't delete the space from devspace cloud. (Internal server error)

Thanks!

**Comment by FabianKramm** [comment]
@Mokto thanks for opening this issue! I fixed this issue with version v0.2.7, as a workaround you could also recreate the namespace and then delete it via `devspace remove space`.

**Comment by FabianKramm** [comment]
@Mokto good catch, that is actually a different problem, you can just assign the namespace any label and this problem should be gone

**Comment by Mokto** [comment]
It worked ! Thanks 👍
