### ISSUE TITLE
[4.4.0] Got an error when adding another provider

### ISSUE THREAD

**Issue by Mokto** [devspace-cloud/devspace-cloud#19]
Hi,

It seems we can't add external providers anymore since 4.4.0.

I tried doing : `devspace add provider devspace.xxx.com` (my custom devspace provider, that is accessible).

The command returns : `Cloud provider not found! Did you run 'devspace add provider [url]'`.

It's only the case for new members of the team we have here. Note: devspace.xxx.com is accessible.

Thanks!

**Comment by FabianKramm** [comment]
@Mokto thanks for reporting! You are right, seems there is a bug with adding new providers in the latest version, I will a release a fix for this today!

**Comment by Mokto** [comment]
It works with 4.5.0.

Thanks!

**Comment by FabianKramm** [comment]
@Mokto should be fixed with devspace v4.5.0
