### ISSUE TITLE
I can't add on premise provider

### ISSUE THREAD

**Issue by base16soft** [devspace-cloud/devspace-cloud#20]
When I run the command in README to add a new provider, devspace ask to add first.

```
# devspace use provider devspace.domain.net.br -n devspace-cloud
[fatal]  Error provider devspace.domain.net.br does not exist! Did you run `devspace add provider devspace.domain.net.br` first?
```

But when I try to add with the access key:

```
[info]   Unable to open web browser for login page.
Please follow these instructions for manually loggin in:

  1. Open this URL in a browser: https://devspace.domain.net.br/settings/access-keys
  2. After logging in, click the 'Create Key' button
  3. Enter a key name (e.g. my-key) and click 'Create Access Key'
  4. Copy the generated key from the input field

? 5. Enter the access key here: ********************************

[fatal]  log into provider: Login: login: get token: token save: Couldn't find provider devspace.domain.net.br

```

I'm using Azure AKS and I can acess with kubectl. I followed the steps, but always get the same error. Please help.

Regards

**Comment by LukasGentele** [comment]
@base16soft Thanks for reporting this. It seems like DevSpace is unable to reach the GraphQL API of your DevSpace Cloud instance. 

Let's try to narrow down the problem:
1. Is your on-prem installation of DevSpace Cloud running on this domain: `devspace.domain.net.br` ? Can you access it in the browser? 
2. Are you running DevSpace inside a special terminal/environment which may have a different network setup than your host computer, e.g. running DevSpace inside a VM or Docker container?
3. Can you run this command in the same terminal you are using for DevSpace: `curl http://devspace.domain.net.br/graphql`
What's the output of that?

**Comment by base16soft** [comment]
Hi @LukasGentele 

1: I can access it in the browser:
![image](https://user-images.githubusercontent.com/113600/74186368-3e406880-4c29-11ea-8105-eaee352982ac.png)

2: Devspace is running on kubernets on Azure. I'm trying to access from a VM on Azure conected by ssh.

3: # curl https://devspace.repassa.net.br/graphql
{"path":"$","error":"resource does not exist","code":"not-found"}%

Regards,
Augusto

**Comment by LukasGentele** [comment]
@FabianKramm any idea on what could be wrong here?

**Comment by FabianKramm** [comment]
@base16soft are you using the newest version of `devspace`, `4.5.0`?

**Comment by base16soft** [comment]
I´m on latest version of devspace. I'll try to reinstall kubernets and try to install again, because when I remove the namespace from kubernets and deploy devspace again, it doen't ask for a domain or database password.

**Comment by LukasGentele** [comment]
It is normal that DevSpace remembers the values for variables you specified. I just talked to @FabianKramm about this issue and seems like it is a bug in DevSpace which is already fixed but not released yet. Sorry about that. We plan to release a new version tomorrow, so please upgrade the CLI an try again tomorrow once the release is out.

**Comment by base16soft** [comment]
I see... OK, no problem... I'll wait for the new release, try again and keep you update. Thanks!

**Comment by base16soft** [comment]
Hi, I was able to upgrade CLI and install devspace-cloud. But now the error has changed:

# devspace sync
start sync: download sync helper: Couldn't find sync helper in github release v4.5.1 at url https://github.com/devspace-cloud/devspace/releases/tag/v4.5.1
