### ISSUE TITLE
Bug when first installing DevSpace On-Premise Edition via Helm

### ISSUE THREAD

**Issue by xXKynarethXx** [devspace-cloud/devspace-cloud#34]
Hello,
I am encountering a problem when first installing DevSpace On-Premise Edition via Helm.

**Error**: 
"Error: template: devspace-cloud/templates/auth/deployment.yaml:49:22: executing "devspace-cloud/templates/auth/deployment.yaml" at <.Values.auth.liveness>: nil pointer evaluating interface {}.liveness"

**Steps to reproduce**:
- Launch a one-node-cluster with RKE on Ubuntu18.04
- Install DevSpace On-Premise with the provided helm command in your documentation.

There is a open [issue](https://github.com/helm/helm/issues/7485) at helm regarding this, but do you have a workaround for this problem?

Thanks very much!

**Comment by FabianKramm** [comment]
@xXKynarethXx thanks for reporting this issue! Should be fixed with v0.3.1
