### ISSUE TITLE
Images missed in docker official registry

### ISSUE THREAD

**Issue by wu-yafeng** [devspace-cloud/devspace-cloud#4]
Following registry  of 'devspace-cloud' used was not found in hub.docker.com
devspacecloud/auth:0.0.6
![image](https://user-images.githubusercontent.com/25654404/64932551-76a66b00-d872-11e9-9107-2e28c8ccb90a.png)

devspacecloud/hasura:0.0.4

![image](https://user-images.githubusercontent.com/25654404/64932560-845bf080-d872-11e9-9224-ec235db1ba2f.png)

devspacecloud/hasura-init:0.0.5

![image](https://user-images.githubusercontent.com/25654404/64932588-bf5e2400-d872-11e9-84f5-d54094122580.png)

**Comment by FabianKramm** [comment]
@wu-yafeng thanks for opening this issue! We were restructuring the project in the last couple of days, which leaded to the issue you encountered. This should be fixed now with DevSpace Cloud version 0.1.0.
