### ISSUE TITLE
Encountering error about missing spec.selector when running deploy-devspace-cloud

### ISSUE THREAD

**Issue by KaelBaldwin** [devspace-cloud/devspace-cloud#5]
```[fatal]  Error deploying devspace-cloud: Unable to deploy helm chart: helm install: rpc error: code = Unknown desc = release devspace-cloud failed: Deployment.apps "devspace-ui" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"devspace-ui"}: `selector` does not match template `labels`]```

**Comment by KaelBaldwin** [comment]
Our kubernetes version is 1.14, our kubectl version is 1.15

**Comment by FabianKramm** [comment]
@KaelBaldwin thanks for opening this issue! This should be fixed with the newest version.
